/* ============================================================
   foodgroups.js — à quelle famille appartient chaque ingrédient.

   Sert aux filtres : « sans viande », « sans porc », « plats de
   gibier »… Les bouillons et sauces d'origine animale figurent à
   part : ils ne font pas d'un plat un plat de poisson, mais ils
   empêchent de le dire végétarien.

   Fichier engendré par scripts/make-foodgroups.mjs — ne pas
   modifier à la main : corrigez plutôt les listes du script.
   ============================================================ */
const FOOD_GROUPS = {
  pork: ['alheira_sausage', 'andouille', 'andouillette', 'bayonne_ham', 'beef_trotters', 'chorizo', 'farinheira', 'ground_pork', 'guanciale', 'ham', 'hot_dog_sausage', 'jinhua_ham', 'lard', 'lardons', 'marinated_pork', 'montbeliard_sausage', 'naem_sausage', 'nduja', 'pancetta', 'pig_caul', 'pinkel_sausage', 'pork_belly', 'pork_blood', 'pork_bones', 'pork_broth', 'pork_chitterlings', 'pork_chops', 'pork_crackling', 'pork_cracklings', 'pork_ear', 'pork_ears', 'pork_fat', 'pork_fatback', 'pork_floss', 'pork_head', 'pork_heart', 'pork_intestines', 'pork_kidney', 'pork_knuckle', 'pork_liver', 'pork_loin', 'pork_lung', 'pork_ribs', 'pork_rind', 'pork_rinds', 'pork_roll', 'pork_sausage', 'pork_shank', 'pork_shoulder', 'pork_skin', 'pork_snout', 'pork_stomach', 'pork_tail', 'pork_tongue', 'pork_tripe', 'pork_trotters', 'prosciutto', 'salami', 'salt_pork', 'salted_pork', 'sausage_casings', 'serrano_ham', 'smoked_bacon', 'smoked_ham', 'smoked_pork_belly', 'smoked_pork_collar', 'smoked_pork_loin', 'smoked_pork_ribs', 'strasbourg_sausage', 'toulouse_sausage'],
  beef: ['beef_bones', 'beef_brisket', 'beef_cheek', 'beef_chuck', 'beef_dripping', 'beef_heart', 'beef_kidney', 'beef_liver', 'beef_ribeye', 'beef_round', 'beef_rump', 'beef_shank', 'beef_short_ribs', 'beef_shoulder', 'beef_sirloin', 'beef_skirt', 'beef_slices', 'beef_steak', 'beef_suet', 'beef_tallow', 'beef_tbone', 'beef_tenderloin', 'beef_tendon', 'beef_tongue', 'beef_tripe', 'bone_marrow', 'carne_seca', 'cecina', 'charque', 'corned_beef', 'dried_beef', 'ground_beef', 'ground_veal', 'marrow_bone', 'ox_blood_curd', 'oxtail', 'picanha', 'salted_beef', 'sirloin_steak', 'tripe', 'veal', 'veal_chop', 'veal_escalope', 'veal_foot', 'veal_shank', 'veal_shoulder'],
  poultry: ['bombay_duck', 'chicken', 'chicken_bones', 'chicken_breast', 'chicken_gizzards', 'chicken_legs', 'chicken_liver', 'chicken_salt', 'chicken_thighs', 'chicken_wings', 'duck', 'duck_blood', 'duck_blood_curd', 'duck_bones', 'duck_breast', 'duck_confit', 'duck_fat', 'duck_gizzards', 'duck_intestines', 'duck_legs', 'duck_liver', 'foie_gras', 'ground_chicken', 'hen', 'smoked_chicken', 'turkey', 'turkey_breast', 'whole_duck'],
  lamb: ['goat_blood', 'goat_heart', 'goat_liver', 'goat_meat', 'goat_pepper', 'goat_shoulder', 'goat_stomach', 'goat_tripe', 'ground_lamb', 'kazy_sausage', 'lamb', 'lamb_bones', 'lamb_chops', 'lamb_fat', 'lamb_kidney', 'lamb_leg', 'lamb_liver', 'lamb_ribs', 'lamb_sausage', 'lamb_shank', 'lamb_shoulder', 'mutton_shoulder', 'mutton_tallow', 'ram_testicles', 'sheep_blood', 'sheep_head', 'sheep_pluck', 'sheep_suet', 'wind_dried_mutton'],
  game: ['guinea_pig', 'horse_meat', 'kangaroo', 'partridge', 'reindeer', 'reindeer_tongue', 'venison', 'whelks', 'wild_boar'],
  rabbit: ['rabbit'],
  fish: ['anchovies', 'anchovy_fillets', 'bonito', 'bonito_flakes', 'canned_salmon', 'canned_tuna', 'carp', 'catfish', 'caviar', 'cod', 'cod_fillet', 'crawfish_tails', 'crocodile', 'cured_salmon', 'dogfish', 'dried_fish', 'dried_herring', 'eel', 'fermented_anchovy_sauce', 'fermented_fish', 'fish_cake', 'fish_head', 'flying_fish', 'freshwater_fish', 'greenland_shark', 'grouper', 'haddock_fillets', 'hilsa_fish', 'kingfish', 'lamprey', 'mackerel', 'mandarin_fish', 'monkfish', 'pickled_herring', 'pike', 'pollock_roe', 'pufferfish', 'red_snapper', 'rockfish', 'salmon', 'salmon_roe', 'salt_cod', 'salted_anchovies', 'salted_fish', 'salted_herring', 'salted_jellyfish', 'salted_salmon', 'sardines', 'scabbard_fish', 'sea_bass', 'sea_bream', 'small_fish', 'smoked_dried_tuna', 'smoked_fish', 'smoked_haddock', 'smoked_trout', 'stockfish', 'tilapia', 'trout', 'tuna', 'white_fish', 'whitefish', 'whiting', 'whole_fish'],
  seafood: ['baby_octopus', 'baby_squid', 'barnacles', 'clams', 'cockles', 'coconut_crab', 'conch', 'crab', 'crab_claws', 'crab_meat', 'crayfish', 'crayfish_powder', 'cuttlefish', 'dried_abalone', 'dried_scallops', 'dried_shrimp', 'dried_squid', 'dungeness_crab', 'giant_clam', 'king_crab_legs', 'land_crab', 'langoustines', 'limpets', 'lobster', 'mussels', 'octopus', 'oysters', 'razor_clams', 'river_prawns', 'salted_shrimp', 'scallops', 'sea_urchin', 'shrimp', 'shrimp_chips', 'small_shrimp', 'smoked_shrimp', 'snails', 'spot_prawns', 'squid', 'squid_ink', 'wedge_clams'],
  fish_trace: ['anchovy_broth', 'dashi_stock', 'fish_broth', 'fish_sauce', 'oyster_sauce', 'salted_shrimp', 'shrimp_paste', 'worcestershire'],
  meat_trace: ['beef_bones', 'beef_broth', 'beef_stock', 'chicken_broth', 'gelatin', 'lamb_bones', 'lard', 'marshmallows', 'pig_caul', 'pork_bones'],
  alcohol: ['akvavit', 'amber_rum', 'apple_cider', 'armagnac', 'barolo_wine', 'beer', 'brandy', 'cachaca', 'calvados', 'dark_rum', 'dry_cider', 'irish_whiskey', 'kirsch', 'madeira_wine', 'marsala', 'mirin', 'ouzo', 'pastis', 'pisco', 'port_wine', 'prosecco', 'red_wine', 'rice_wine', 'rum', 'sake', 'shaoxing_wine', 'sherry', 'sparkling_wine', 'stout', 'vodka', 'whisky', 'white_rum', 'white_wine']
};
