/* ============================================================
   Lexique des ingrédients — [fr, en]
   ============================================================ */
const ING = {
abura_age:["tofu frit en feuilles","fried tofu pouches"],
  acai_pulp: ["pulpe d'açaï", 'açaí pulp'],
achiote_paste:["pâte d'achiote","achiote paste"],
agar_agar:["agar-agar","agar-agar"],
aged_kimchi:["kimchi bien fermenté","aged kimchi"],
aibika_leaves:["feuilles d'aibika","aibika leaves"],
aji_amarillo_paste:["pâte d'ají amarillo","ají amarillo paste"],
aji_limo:["piment ají limo","ají limo chilli"],
aji_panca_paste:["pâte de piment aji panca","aji panca paste"],
akvavit:["akvavit", "akvavit"],
alder_chips:["copeaux d'aulne","alder chips"],
aleppo_pepper:["piment d'Alep","Aleppo pepper"],
alheira_sausage:["alheiras","alheira sausages"],
allspice:["piment de la Jamaïque","allspice"],
almond_extract:["extrait d'amande amère", "almond extract"],
almonds:["amandes","almonds"],
  alum: ['alun alimentaire', 'food-grade alum'],
amaretti:["amaretti", "amaretti biscuits"],
  amber_rum: ['rhum ambré', 'amber rum'],
  amchur: ['poudre de mangue verte', 'amchur powder'],
american_cheese:["fromage fondu en tranches","American cheese slices"],
ancho_chili:["piment ancho","ancho chilli"],
anchovies:["anchois frais","fresh anchovies"],
anchovy_broth:["bouillon d'anchois","anchovy broth"],
anchovy_fillets:["filets d'anchois","anchovy fillets"],
andouille:["andouille","andouille sausage"],
andouillette:["andouillettes","andouillette sausages"],
  angostura_bitters: ['amer aromatique', 'aromatic bitters'],
anise_seeds:["graines d'anis","anise seeds"],
anisette:["anisette","anisette liqueur"],
  annatto: ['roucou', 'annatto'],
aperol:["Aperol","Aperol"],
appenzeller_cheese:["appenzeller", "appenzeller cheese"],
apple:["pomme","apple"],
  apple_cider: ['cidre doux', 'sweet apple cider'],
apple_jam:["confiture de pommes","apple jam"],
apple_juice:["jus de pomme","apple juice"],
apple_sauce:["compote de pommes", "apple sauce"],
apricot_jam:["confiture d'abricot","apricot jam"],
arborio_rice:["riz arborio","arborio rice"],
arctic_char:["omble chevalier","Arctic char"],
arepa:["arepas","arepas"],
armagnac:["armagnac","armagnac"],
artichoke:["artichauts", "artichokes"],
arugula:["roquette", "rocket"],
asafoetida:["asafœtida","asafoetida"],
  ash_gourd: ['courge cendrée', 'ash gourd'],
  asian_pear: ['poire asiatique', 'Asian pear'],
asparagus:["asperges vertes","green asparagus"],
attieke:["attiéké","attiéké"],
aubergine:["aubergines","aubergines"],
avocado:["avocats","avocados"],
awamori:["awamori","awamori"],
awara_paste:["pâte d'awara","awara paste"],
ayib_cheese:["fromage frais ayib","ayib fresh cheese"],
azuki_beans:["haricots azuki sucrés","sweet azuki beans"],
  baby_octopus: ['petit poulpe', 'baby octopus'],
baby_potatoes:["pommes de terre grenaille","baby potatoes"],
baby_squid:["chipirons","baby squid"],
bagels:["bagels","bagels"],
baguette:["baguette","baguette"],
baharat:["baharat","baharat"],
baked_beans:["haricots à la tomate","baked beans"],
baking_powder:["levure chimique","baking powder"],
baking_soda:["bicarbonate de soude","bicarbonate of soda"],
  bamboo_leaves: ['feuilles de bambou', 'bamboo leaves'],
bamboo_shoots:["pousses de bambou","bamboo shoots"],
banana:["banane","banana"],
banana_flower:["fleur de bananier","banana flower"],
banana_leaf:["feuille de bananier","banana leaf"],
banana_leaves:["feuilles de bananier","banana leaves"],
baobab_leaf_powder:["poudre de feuilles de baobab","baobab leaf powder"],
barbecue_sauce:["sauce barbecue","barbecue sauce"],
barberries:["épines-vinettes","barberries"],
barley:["orge","barley"],
barley_flour:["farine d'orge","barley flour"],
barley_malt:["malt d'orge", "barley malt"],
barnacles:["pouces-pieds","goose barnacles"],
barolo_wine:["vin de Barolo","Barolo wine"],
barramundi:["barramundi","barramundi"],
basil:["basilic","basil"],
basmati_rice:["riz basmati","basmati rice"],
bay_leaf:["feuilles de laurier","bay leaves"],
bayonne_ham:["jambon de Bayonne","Bayonne ham"],
bean_sprouts:["germes de soja","bean sprouts"],
beaufort_cheese:["beaufort","Beaufort cheese"],
beef_bones:["os de bœuf","beef bones"],
beef_brisket:["poitrine de bœuf","beef brisket"],
beef_broth:["bouillon de bœuf","beef broth"],
  beef_cheek: ['joue de bœuf', 'beef cheek'],
beef_chuck:["paleron de bœuf","beef chuck"],
beef_dripping:["graisse de rôti de bœuf","beef dripping"],
beef_heart:["cœur de bœuf","beef heart"],
beef_kidney:["rognons de bœuf","beef kidney"],
beef_liver:["foie de bœuf","beef liver"],
beef_ribeye:["entrecôte de bœuf","beef ribeye"],
beef_round:["gîte de bœuf","beef round"],
beef_rump:["tende de tranche de bœuf", "beef rump"],
beef_sausage:["saucisse de bœuf","beef sausage"],
beef_shank:["jarret de bœuf","beef shank"],
beef_short_ribs:["plat de côtes de bœuf","beef short ribs"],
beef_shoulder:["épaule de bœuf","beef shoulder"],
beef_sirloin:["faux-filet de bœuf","beef sirloin"],
beef_skirt:["hampe de bœuf", "beef skirt"],
beef_slices:["fines tranches de bœuf","beef slices"],
beef_steak:["steaks de bœuf","beef steaks"],
beef_stock:["fond de bœuf","beef stock"],
beef_suet:["graisse de rognon de bœuf", "beef suet"],
beef_tallow:["graisse de bœuf","beef tallow"],
beef_tbone:["côte de bœuf avec l'os", "T-bone steak"],
beef_tenderloin:["filet de bœuf","beef tenderloin"],
beef_tendon:["tendon de bœuf","beef tendon"],
beef_tongue:["langue de bœuf","beef tongue"],
beef_tripe:["tripes de bœuf","beef tripe"],
beef_trotters:["pieds de bœuf","cow's feet"],
beer:["bière blonde","lager beer"],
beeswax:["cire d'abeille alimentaire","food-grade beeswax"],
beetroot:["betteraves","beetroots"],
bell_pepper:["poivron","bell pepper"],
berbere:["berbéré","berbere spice"],
berry_jam:["confiture de baies","berry jam"],
bhajia_batter:["pâte à beignets","fritter batter"],
bijao_leaves:["feuilles de bijao","bijao leaves"],
bird_eye_chili:["piment oiseau","bird's-eye chilli"],
biryani_masala:["masala à biryani","biryani masala"],
bison:["bison haché","minced bison"],
  bitter_cassava: ['manioc amer', 'bitter cassava'],
bitter_melon:["margose","bitter melon"],
black_beans:["haricots noirs","black beans"],
black_cardamom:["cardamome noire","black cardamom"],
black_cherries:["cerises noires","black cherries"],
  black_chickpeas: ['pois chiches noirs', 'black chickpeas'],
black_eyed_peas:["haricots niébé","black-eyed peas"],
black_olives:["olives noires","black olives"],
black_peppercorns:["poivre noir en grains","black peppercorns"],
  black_salt: ["sel noir de l'Himalaya", 'black salt'],
black_sesame_seeds:["graines de sésame noir","black sesame seeds"],
black_tea:["thé noir","black tea"],
black_treacle:["mélasse noire","black treacle"],
black_truffle:["truffe noire", "black truffle"],
black_vinegar:["vinaigre noir de Chinkiang","Chinkiang black vinegar"],
blackberries:["mûres","blackberries"],
  blackberry_jam: ['confiture de mûres', 'blackberry jam'],
blood_sausage:["boudin noir","blood sausage"],
blue_cheese:["fromage bleu","blue cheese"],
blue_fenugreek:["fenugrec bleu","blue fenugreek"],
blueberries:["myrtilles sauvages","wild blueberries"],
boiling_water:["eau bouillante","boiling water"],
bok_choy:["pak-choï","bok choy"],
bolillo_bread:["pain bolillo","bolillo bread"],
bologna:["mortadelle","bologna sausage"],
bomba_rice:["riz bomba","bomba rice"],
  bombay_duck: ['poisson-lézard', 'Bombay duck'],
bone_marrow:["moelle de bœuf","bone marrow"],
bonito:["bonite fraîche","fresh bonito"],
bonito_flakes:["copeaux de bonite","bonito flakes"],
borage:["bourrache","borage"],
botifarra:["botifarra","botifarra sausage"],
  bottle_gourd: ['courge bouteille', 'bottle gourd'],
bouillon_cube:["cube de bouillon","stock cube"],
bourbon:["bourbon","bourbon"],
brandy:["brandy","brandy"],
bratwurst:["bratwurst","bratwurst"],
bread:["pain","bread"],
bread_dumplings:["knedlíky","bread dumplings"],
bread_flour:["farine de gruau","strong bread flour"],
bread_roll:["petit pain","bread roll"],
breadcrumbs:["chapelure","breadcrumbs"],
breadfruit:["fruit à pain","breadfruit"],
brede_mafana:["brèdes mafana","brèdes mafana leaves"],
brezel:["bretzels","pretzels"],
brioche:["brioche","brioche"],
broad_beans:["fèves","broad beans"],
brocciu:["brocciu","brocciu cheese"],
broken_rice:["riz brisé","broken rice"],
brown_ale:["bière brune","brown ale"],
brown_cheese:["brunost", "brunost brown cheese"],
brown_lentils:["lentilles brunes","brown lentils"],
brown_sugar:["sucre roux","brown sugar"],
bryndza_cheese:["bryndza","bryndza cheese"],
bucatini:["bucatini","bucatini"],
buckwheat_flour:["farine de sarrasin","buckwheat flour"],
buckwheat_groats:["sarrasin grillé","toasted buckwheat groats"],
buckwheat_noodles:["nouilles de sarrasin","buckwheat noodles"],
buffalo_milk:["lait de bufflonne","buffalo milk"],
bulgur:["boulgour","bulgur"],
burdock:["bardane","burdock root"],
burger_buns:["pains à burger","burger buns"],
  bush_plum: ['prune kakadu', 'Kakadu plum'],
bush_tomato:["tomate du bush","bush tomato"],
butter:["beurre","butter"],
buttermilk:["babeurre","buttermilk"],
button_mushrooms:["champignons de Paris","button mushrooms"],
cabbage:["chou blanc","white cabbage"],
cabrales_cheese:["cabrales","Cabrales cheese"],
cachaca:["cachaça","cachaça"],
caerphilly_cheese:["caerphilly","Caerphilly cheese"],
cajun_seasoning:["assaisonnement cajun","Cajun seasoning"],
calcots:["calçots (oignons nouveaux catalans)","calçots (Catalan spring onions)"],
callaloo:["feuilles de dachine","dasheen leaves"],
calvados:["calvados","calvados"],
camembert:["camembert bien fait","ripe camembert"],
  camphor_leaves: ['feuilles de camphrier', 'camphor leaves'],
candied_citron:["cédrat confit","candied citron"],
candied_fruit:["fruits confits","candied fruit"],
candied_orange:["orange confite","candied orange"],
candlenut:["noix de bancoul","candlenuts"],
  cane_syrup: ['sirop de canne', 'cane syrup'],
cane_vinegar:["vinaigre de canne","cane vinegar"],
canned_salmon:["saumon en conserve","canned salmon"],
  canned_tomatoes: ['tomates pelées en conserve', 'tinned peeled tomatoes'],
canned_tuna:["thon en conserve","tinned tuna"],
cannellini_beans:["haricots cannellini","cannellini beans"],
cannelloni:["cannellonis","cannelloni tubes"],
capers:["câpres","capers"],
caraway:["cumin des prés","caraway seeds"],
cardamom:["cardamome","cardamom"],
cardoon:["cardon", "cardoon"],
carnaroli_rice:["riz carnaroli","carnaroli rice"],
carne_seca:["viande séchée carne seca","carne seca"],
carom_seeds:["graines d'ajowan","carom seeds"],
carp:["carpe","carp"],
carrot:["carottes","carrots"],
casera_cheese:["fromage casera", "casera cheese"],
  cashews: ['noix de cajou', 'cashew nuts'],
cassareep:["cassaripe","cassareep"],
cassava:["manioc","cassava"],
cassava_flour:["farine de manioc","cassava flour"],
  cassava_juice: ['jus de manioc', 'cassava juice'],
cassava_leaves:["feuilles de manioc","cassava leaves"],
cassava_semolina:["semoule de manioc","cassava semolina"],
cassava_starch:["fécule de manioc","cassava starch"],
catfish:["poisson-chat","catfish"],
cauliflower:["chou-fleur","cauliflower"],
cava:["cava","cava"],
cayenne:["piment de Cayenne","cayenne pepper"],
cayenne_pepper:["poivre de Cayenne","ground cayenne"],
cecina:["cecina","cecina"],
cedar_plank:["planche de cèdre","cedar plank"],
celery:["branches de céleri","celery sticks"],
celery_root:["céleri-rave","celery root"],
celery_salt:["sel de céleri","celery salt"],
chaat_masala:["chaat masala","chaat masala"],
  chana_dal: ['pois chiches cassés', 'chana dal'],
  chancaca: ['chancaca', 'chancaca'],
char_siu:["porc char siu","char siu pork"],
charque:["charque","charque"],
chayote:["chayottes","chayote"],
cheddar_cheese:["cheddar","cheddar cheese"],
cheese:["fromage à pâte pressée","firm cheese"],
cheese_curds:["fromage en grains","cheese curds"],
cheese_slices:["tranches de fromage","cheese slices"],
cherries:["cerises","cherries"],
  cherry_jam: ['confiture de cerises noires', 'black cherry jam'],
cherry_tomato:["tomate cerise","cherry tomato"],
chervil:["cerfeuil", "chervil"],
chestnut_flour:["farine de châtaigne","chestnut flour"],
chestnuts:["châtaignes","chestnuts"],
chicha_de_maiz:["chicha de maïs","maize chicha"],
chicken:["poulet","chicken"],
  chicken_bones: ['carcasses de poulet', 'chicken bones'],
chicken_breast:["blancs de poulet","chicken breast"],
chicken_broth:["bouillon de volaille","chicken broth"],
chicken_gizzards:["gésiers de volaille","chicken gizzards"],
chicken_legs:["cuisses de poulet entières","whole chicken legs"],
chicken_liver:["foies de volaille","chicken livers"],
  chicken_salt: ['sel de poulet', 'chicken salt'],
chicken_thighs:["cuisses de poulet","chicken thighs"],
chicken_wings:["ailes de poulet","chicken wings"],
chickpea_flour:["farine de pois chiche","chickpea flour"],
chickpeas:["pois chiches","chickpeas"],
chicory:["chicorée","chicory"],
chile_cobanero:["piment cobanero","cobanero chilli"],
  chile_de_arbol: ['piment de arbol', 'chile de árbol'],
chili_flakes:["piment en flocons","chilli flakes"],
chili_oil:["huile pimentée","chilli oil"],
chili_pepper:["piment frais","chilli pepper"],
chili_powder:["chili en poudre","chili powder"],
  chili_sauce: ['sauce pimentée', 'chilli sauce'],
  chimol: ['chimol', 'chimol'],
  chinese_chives_flower: ['fleurs de ciboule chinoise', 'chive flower paste'],
chipotle:["piment chipotle","chipotle chilli"],
chistorra:["chistorra","chistorra sausage"],
chives:["ciboulette","chives"],
chochos:["lupins chochos","chocho lupins"],
  chocolate_sprinkles: ['vermicelles de chocolat', 'chocolate sprinkles'],
choricero_peppers:["poivrons choriceros séchés","dried choricero peppers"],
chorizo:["chorizo","chorizo"],
chourico:["chouriço","chouriço"],
chunjang:["pâte de soja noire chunjang","chunjang black bean paste"],
chuno:["chuño","chuño"],
churek_bread:["pain churek","churek bread"],
cider_vinegar:["vinaigre de cidre","cider vinegar"],
cilantro:["coriandre fraîche","cilantro"],
cinnamon:["cannelle","cinnamon"],
  cinnamon_stick: ['bâton de cannelle', 'cinnamon stick'],
clams:["palourdes","clams"],
clarified_butter:["beurre clarifié","clarified butter"],
clove:["clou de girofle","clove"],
cloves:["clous de girofle","cloves"],
coalho_cheese:["fromage coalho","coalho cheese"],
coarse_salt:["gros sel","coarse salt"],
cockles:["coques","cockles"],
cocoa_butter:["beurre de cacao","cocoa butter"],
cocoa_powder:["cacao en poudre","cocoa powder"],
coconut:["noix de coco","coconut"],
coconut_crab:["crabe de cocotier","coconut crab"],
coconut_cream:["crème de coco","coconut cream"],
coconut_milk:["lait de coco","coconut milk"],
coconut_oil:["huile de coco","coconut oil"],
cod:["cabillaud","cod"],
cod_fillet:["filets de cabillaud","cod fillets"],
coffee:["café fort","strong coffee"],
collard_greens:["chou cavalier","collard greens"],
colombo_spice:["épices colombo","colombo spice blend"],
comte_cheese:["comté","Comté cheese"],
conch:["lambi","conch"],
condensed_milk:["lait concentré sucré","condensed milk"],
cooked_rice:["riz cuit de la veille","day-old cooked rice"],
cooked_wheat:["blé cuit pour pastiera","cooked wheat berries"],
coriander_seeds:["graines de coriandre","coriander seeds"],
corn:["épi de maïs","corn"],
corn_bread:["pain de maïs","maize bread"],
corn_cobs:["épis de maïs","corn cobs"],
corn_flour:["farine de maïs fine","maize flour"],
  corn_husks: ['feuilles de maïs séchées', 'dried corn husks'],
corn_kernels:["grains de maïs","corn kernels"],
corn_masa:["masa de maïs","corn masa"],
  corn_syrup: ['sirop de maïs', 'corn syrup'],
corn_tortillas:["tortillas de maïs","corn tortillas"],
corned_beef:["corned-beef","corned beef"],
cornmeal:["farine de maïs","cornmeal"],
cornstarch:["fécule de maïs","cornflour"],
couscous_semolina:["semoule à couscous","couscous semolina"],
crab:["crabe","crab"],
  crab_claws: ['pinces de crabe', 'crab claws'],
crab_meat:["chair de crabe","crab meat"],
cracked_corn:["maïs concassé","cracked corn"],
cracked_wheat:["blé concassé","cracked wheat"],
cranberry_jam:["confiture de canneberges","cranberry preserve"],
crawfish_tails:["queues d'écrevisses","crawfish tails"],
crayfish:["écrevisses moulues","crayfish"],
crayfish_powder:["crustacés séchés moulus","ground crayfish"],
cream_cheese:["fromage à la crème","cream cheese"],
crescenza_cheese:["crescenza (fromage frais italien)","crescenza cheese"],
  crocodile: ['queue de crocodile', 'crocodile tail'],
croutons:["croûtons","croutons"],
cuban_bread:["pain cubain","Cuban bread"],
cucumber:["concombre","cucumber"],
culantro:["culantro","culantro"],
cumin:["cumin","cumin"],
  cupuacu_pulp: ['pulpe de cupuaçu', 'cupuaçu pulp'],
cured_salmon:["saumon saumuré","cured salmon"],
curly_kale:["chou frisé","curly kale"],
currants:["raisins de Corinthe","currants"],
curry_leaves:["feuilles de curry","curry leaves"],
  curry_paste: ['pâte de curry', 'curry paste'],
curry_powder:["curry en poudre","curry powder"],
cuttlefish:["seiches", "cuttlefish"],
daikon:["radis blanc","daikon"],
daikon_radish:["radis daïkon","daikon radish"],
dandelion_greens:["pissenlits","dandelion greens"],
  danmuji: ['radis jaune mariné', 'pickled yellow radish'],
dark_chocolate:["chocolat noir","dark chocolate"],
dark_rum:["rhum brun","dark rum"],
dark_soy_sauce:["sauce soja noire","dark soy sauce"],
dashi_stock:["bouillon dashi","dashi stock"],
date_syrup:["sirop de datte","date syrup"],
dates:["dattes", "dates"],
datshi_cheese:["datshi","datshi cheese"],
desiccated_coconut:["noix de coco râpée","desiccated coconut"],
digestive_biscuits:["biscuits digestive","digestive biscuits"],
dijon_mustard:["moutarde de Dijon","Dijon mustard"],
dill:["aneth","dill"],
  doenjang: ['pâte de soja coréenne', 'doenjang'],
dogfish:["aiguillat","dogfish"],
doubanjiang:["pâte de fèves pimentée","doubanjiang"],
  dried_abalone: ['ormeaux séchés', 'dried abalone'],
dried_apricots:["abricots secs","dried apricots"],
dried_beef:["viande de bœuf séchée","dried beef"],
dried_black_lime:["citron noir séché","dried black lime"],
dried_chickpeas:["pois chiches secs","dried chickpeas"],
dried_chili:["piments séchés","dried chillies"],
dried_figs:["figues séchées","dried figs"],
dried_fish:["poisson séché","dried fish"],
  dried_flounder: ['plie séchée', 'dried flounder'],
  dried_herring: ['hareng séché', 'dried herring'],
dried_lime:["citron séché","dried lime"],
dried_mint:["menthe séchée","dried mint"],
dried_morels:["morilles séchées","dried morels"],
dried_mushrooms:["champignons séchés","dried mushrooms"],
dried_nyora_pepper:["poivron séché ñora","dried ñora pepper"],
dried_peaches:["pêches séchées","dried peaches"],
dried_pears:["poires séchées","dried pears"],
dried_porcini:["cèpes séchés","dried porcini"],
  dried_potato: ['pomme de terre séchée', 'dried potato'],
  dried_rose_petals: ['pétales de rose séchés', 'dried rose petals'],
  dried_scallops: ['pétoncles séchés', 'dried scallops'],
  dried_sea_cucumber: ['concombre de mer séché', 'dried sea cucumber'],
dried_shrimp:["crevettes séchées","dried shrimp"],
dried_sweet_peppers:["poivrons doux séchés","dried sweet peppers"],
dried_yogurt_balls:["boules de yaourt séché","dried yoghurt balls"],
  drumstick: ['gousses de moringa', 'drumstick pods'],
dry_cider:["cidre sec","dry cider"],
dry_yeast:["levure sèche","dried yeast"],
duck:["canard","duck"],
  duck_blood: ['sang de canard', 'duck blood'],
  duck_blood_curd: ['sang de canard caillé', 'congealed duck blood'],
  duck_bones: ['carcasse de canard', 'duck bones'],
duck_breast:["magrets de canard","duck breasts"],
duck_confit:["cuisses de canard confites","duck confit legs"],
duck_fat:["graisse de canard","duck fat"],
  duck_gizzards: ['gésiers de canard', 'duck gizzards'],
  duck_intestines: ['intestins de canard', 'duck intestines'],
duck_legs:["cuisses de canard","duck legs"],
  duck_liver: ['foie de canard', 'duck liver'],
dulce_de_leche:["dulce de leche","dulce de leche"],
dungeness_crab:["crabes dormeurs","Dungeness crabs"],
eel:["anguille", "eel"],
egg:["œufs","eggs"],
egg_noodles:["nouilles aux œufs","egg noodles"],
egg_white:["blancs d'œufs","egg whites"],
egg_yolk:["jaunes d'œufs","egg yolks"],
eggplant:["aubergine","eggplant"],
egusi_seeds:["graines d'egusi","egusi seeds"],
emmental:["emmental râpé","grated emmental"],
emmental_cheese:["emmental","Emmental cheese"],
endive:["endives", "chicory endives"],
english_muffins:["muffins anglais","English muffins"],
  eno: ['poudre effervescente eno', 'eno fruit salt'],
enoki_mushrooms:["champignons enoki","enoki mushrooms"],
epazote:["épazote","epazote"],
epis:["épis créole","Haitian epis"],
espelette_pepper:["piment d'Espelette","Espelette pepper"],
espresso_coffee:["café expresso", "espresso coffee"],
evaporated_milk:["lait évaporé","evaporated milk"],
fabes_beans:["haricots fabes des Asturies","fabes beans"],
farinheira:["farinheira","farinheira sausage"],
farmer_cheese:["fromage blanc égoutté","farmer's cheese"],
  farsan: ['mélange croustillant farsan', 'farsan mix'],
fava_beans:["fèves brunes","fava beans"],
fennel:["bulbe de fenouil","fennel bulb"],
  fennel_seed: ['graines de fenouil', 'fennel seeds'],
fenugreek_leaves:["fenugrec séché","dried fenugreek leaves"],
fenugreek_seeds:["graines de fenugrec","fenugreek seeds"],
fermented_black_beans:["haricots noirs fermentés","fermented black beans"],
fermented_brine:["saumure fermentée","fermented brine"],
fermented_cabbage:["chou fermenté","fermented cabbage"],
  fermented_tofu: ['tofu fermenté', 'fermented bean curd'],
feta:["feta","feta"],
filo_pastry:["pâte filo","filo pastry"],
firm_tofu:["tofu ferme","firm tofu"],
fish_broth:["fumet de poisson","fish broth"],
fish_cake:["pâté de poisson","fish cake"],
  fish_head: ['tête de poisson', 'fish head'],
fish_sauce:["sauce de poisson","fish sauce"],
five_spice:["cinq-épices","five-spice powder"],
flank_steak:["bavette de bœuf","flank steak"],
flat_green_beans:["haricots plats","flat green beans"],
flatbread:["pain plat","flatbread"],
  flattened_rice: ['riz aplati', 'flattened rice'],
flax_seeds:["graines de lin","flax seeds"],
flour:["farine","plain flour"],
flour_00:["farine type 00","00 flour"],
flour_tortillas:["tortillas de blé","flour tortillas"],
flying_fish:["poisson volant","flying fish"],
foie_gras:["foie gras","foie gras"],
  fondant: ['fondant pâtissier', 'fondant icing'],
fontina:["fontine", "fontina"],
four_spices:["quatre-épices","four-spice mix"],
freekeh:["frik (blé vert concassé)","freekeh"],
fresh_cheese:["fromage frais","fresh curd cheese"],
fresh_pecorino:["pecorino frais", "fresh pecorino"],
fresh_sausage:["saucisses fraîches","fresh sausages"],
fresh_walnuts:["noix fraîches","fresh walnuts"],
fresh_yeast:["levure fraîche","fresh yeast"],
  freshwater_fish: ["poisson d'eau douce", 'freshwater fish'],
fried_egg:["œuf au plat","fried egg"],
  fried_noodles: ['nouilles frites croustillantes', 'crisp fried noodles'],
fried_onions:["oignons frits","fried onions"],
frisee_lettuce:["frisée","frisée lettuce"],
fromage_blanc:["fromage blanc","fromage blanc"],
frying_oil:["huile de friture","frying oil"],
galangal:["galanga","galangal"],
garam_masala:["garam masala","garam masala"],
gari:["gari de manioc","gari"],
garlic:["ail","garlic"],
garlic_chives:["ciboule chinoise","garlic chives"],
garlic_powder:["ail en poudre","garlic powder"],
  garlic_sauce: ["sauce à l'ail", 'garlic sauce'],
gelatin:["gélatine","gelatine"],
ghee:["ghee","ghee"],
  giant_clam: ['bénitier', 'giant clam'],
giardiniera:["giardiniera","giardiniera"],
gin:["gin","gin"],
ginger:["gingembre frais","fresh ginger"],
ginger_garlic_paste:["pâte d'ail et gingembre","ginger-garlic paste"],
gingerbread:["pain d'épices","gingerbread"],
ginkgo_nuts:["noix de ginkgo","ginkgo nuts"],
ginseng:["ginseng","ginseng"],
glace_cherries:["cerises confites","glacé cherries"],
glass_noodles:["vermicelles de soja","glass noodles"],
  glucose_syrup: ['sirop de glucose', 'glucose syrup'],
glutinous_rice:["riz gluant","glutinous rice"],
glutinous_rice_flour:["farine de riz gluant","glutinous rice flour"],
  goat_blood: ['sang de chèvre', 'goat blood'],
  goat_heart: ['cœur de chèvre', 'goat heart'],
  goat_liver: ['foie de chèvre', 'goat liver'],
goat_meat:["viande de chèvre","goat meat"],
goat_pepper:["piment goat","goat pepper"],
  goat_shoulder: ['épaule de chevreau', 'goat shoulder'],
goat_stomach:["estomac de chevreau", "kid's stomach"],
  goat_tripe: ['panse de chèvre', 'goat stomach lining'],
gochugaru:["piment coréen en poudre","gochugaru"],
gochujang:["pâte de piment gochujang","gochujang"],
  goda_masala: ['goda masala', 'goda masala'],
godamba_roti:["pains godamba","godamba roti"],
gofio:["gofio","gofio"],
goji_berries:["baies de goji","goji berries"],
golden_syrup:["sirop doré","golden syrup"],
gorgonzola:["gorgonzola doux","sweet gorgonzola"],
gouda:["gouda vieux","aged Gouda"],
graham_crackers:["biscuits Graham","Graham crackers"],
grape_leaves:["feuilles de vigne","vine leaves"],
grapes:["raisin","grapes"],
gray_peas:["pois gris","gray peas"],
  green_ants: ['fourmis vertes', 'green ants'],
green_banana:["banane verte","green banana"],
green_beans:["haricots verts","green beans"],
green_cabbage:["chou vert","green cabbage"],
green_chili:["piments verts","green chillies"],
green_jackfruit:["jaque vert","green jackfruit"],
green_lentils:["lentilles vertes","green lentils"],
green_mango:["mangues vertes","green mangoes"],
green_olives:["olives vertes","green olives"],
green_papaya:["papaye verte","green papaya"],
green_pepper:["poivron vert","green pepper"],
green_plantain:["bananes plantain vertes","green plantains"],
green_plums:["prunes vertes","green plums"],
green_seasoning:["green seasoning","green seasoning"],
green_tea:["thé vert gunpowder","gunpowder green tea"],
green_tomatoes:["tomates vertes","green tomatoes"],
greenland_shark:["chair de requin du Groenland","Greenland shark"],
grits:["grits (semoule de maïs)","grits"],
ground_almonds:["poudre d'amandes","ground almonds"],
ground_beef:["bœuf haché","minced beef"],
ground_chicken:["poulet haché","ground chicken"],
ground_ginger:["gingembre moulu","ground ginger"],
ground_lamb:["agneau haché","minced lamb"],
ground_pork:["porc haché","minced pork"],
ground_veal:["veau haché","minced veal"],
grouper:["mérou","grouper"],
gruyere_cheese:["gruyère","Gruyère cheese"],
guajillo_chili:["piment guajillo","guajillo chilli"],
guanciale:["guanciale (joue de porc séchée)","guanciale"],
  guariroba: ['guariroba', 'guariroba palm heart'],
guasca_herb:["guasca","guasca herb"],
  guava_juice: ['jus de goyave', 'guava juice'],
guava_paste:["pâte de goyave","guava paste"],
guindilla_peppers:["piments guindilla au vinaigre","pickled guindilla peppers"],
  guinea_pig: ["cochon d'Inde", 'guinea pig'],
habanero:["habanero","habanero"],
haddock_fillets:["églefins entiers","whole haddock"],
halloumi:["halloumi","halloumi"],
ham:["jambon blanc","cooked ham"],
handkaese:["handkäse", "handkäse"],
hardtack:["pain dur","hardtack"],
harissa:["harissa","harissa"],
hatch_green_chiles:["piments verts de Hatch","Hatch green chiles"],
hawaiian_salt:["sel rouge d'Hawaï","Hawaiian red salt"],
hawaij:["hawaij","hawaij"],
hazelnuts:["noisettes","hazelnuts"],
heavy_cream:["crème liquide entière","double cream"],
hen:["poule","hen"],
hilsa_fish:["hilsa","hilsa fish"],
hoagie_roll:["pain hoagie","hoagie roll"],
hoisin_sauce:["sauce hoisin","hoisin sauce"],
hominy_corn:["maïs blanc mondé","hominy corn"],
honey:["miel","honey"],
horse_meat:["viande de cheval","horse meat"],
horseradish:["raifort","horseradish"],
hot_dog_bun:["pain à hot-dog","hot dog bun"],
hot_dog_buns:["pains à hot-dog","hot dog buns"],
  hot_dog_sausage: ['saucisse de Francfort', 'frankfurter'],
hot_paprika:["paprika fort", "hot paprika"],
hot_pepper:["piment fort","hot chilli"],
hot_sauce:["sauce piquante","hot sauce"],
hot_water:["eau chaude","hot water"],
huacatay:["huacatay","huacatay"],
hulled_wheat:["blé mondé","hulled wheat"],
ice:["glaçons","ice"],
ice_water:["eau glacée","ice water"],
injera:["injera","injera"],
  instant_coffee: ['café soluble', 'instant coffee'],
  instant_noodles: ['nouilles instantanées', 'instant noodles'],
irish_whiskey:["whiskey irlandais","Irish whiskey"],
island_cabbage:["chou des îles","island cabbage"],
jalapeno:["piment jalapeño","jalapeño pepper"],
  jambu: ['jambu', 'jambu'],
jambu_leaves:["feuilles de jambu","jambu leaves"],
jerusalem_artichoke:["topinambours", "Jerusalem artichokes"],
  jinhua_ham: ['jambon de Jinhua', 'Jinhua ham'],
jujube:["jujubes séchés","dried jujubes"],
juniper_berries:["baies de genièvre","juniper berries"],
jute_leaf_powder:["poudre de corète","dried jute leaf powder"],
kaffir_lime_leaves:["feuilles de combava","kaffir lime leaves"],
kajmak:["kajmak","kajmak"],
kama_flour:["farine de kama", "kama flour"],
kamaboko:["kamaboko","kamaboko fish cake"],
  kangaroo: ['filet de kangourou', 'kangaroo fillet'],
kashk:["kashk","kashk"],
kashmiri_chili:["piment du Cachemire","Kashmiri chilli"],
  kava_root: ['racine de kava', 'kava root'],
kazy_sausage:["saucisse kazy","kazy sausage"],
kecap_manis:["kecap manis","kecap manis"],
kefir:["kéfir","kefir"],
ketchup:["ketchup","ketchup"],
  kewra_water: ['eau de pandanus', 'kewra water'],
key_lime_juice:["jus de citron vert key lime","key lime juice"],
khmeli_suneli:["khmeli-souneli","khmeli suneli"],
kimchi:["kimchi","kimchi"],
king_crab_legs:["pattes de crabe royal","king crab legs"],
kingfish:["thazard","kingfish"],
kirsch:["kirsch","kirsch"],
kiwi:["kiwis","kiwis"],
koko_leaves:["feuilles de koko","koko leaves"],
  kokum: ['kokum séché', 'dried kokum'],
kombu:["algue kombu","kombu"],
konjac:["konjac","konjac"],
  kudampuli: ['tamarin de Malabar', 'Malabar tamarind'],
kumara:["kūmara","kūmara"],
kvass:["kvas","kvass"],
ladyfingers:["biscuits à la cuillère", "ladyfinger biscuits"],
lamb:["agneau","lamb"],
lamb_bones:["os d'agneau","lamb bones"],
  lamb_chops: ["côtelettes d'agneau", 'lamb chops'],
lamb_fat:["graisse de mouton","lamb fat"],
lamb_kidney:["rognons d'agneau", "lamb kidneys"],
lamb_leg:["gigot d'agneau","leg of lamb"],
lamb_liver:["foie d'agneau","lamb liver"],
  lamb_ribs: ["côtes d'agneau avec os", 'lamb ribs on the bone'],
lamb_sausage:["saucisses d'agneau","lamb sausages"],
  lamb_shank: ["souris d'agneau", 'lamb shank'],
lamb_shoulder:["épaule d'agneau","lamb shoulder"],
lamprey:["lamproie", "lamprey"],
  land_crab: ['crabe de terre', 'land crab'],
langoustines:["langoustines","langoustines"],
lap_cheong:["saucisses chinoises","lap cheong sausages"],
lard:["saindoux","lard"],
lardons:["lardons","lardons"],
large_tortillas:["grandes tortillas","large tortillas"],
lavash:["lavash","lavash"],
laver_seaweed:["algue laver","laver seaweed"],
leek:["poireaux","leeks"],
lemon:["citrons","lemons"],
lemon_myrtle:["myrte citronné","lemon myrtle"],
lemon_zest:["zeste de citron","lemon zest"],
lemongrass:["citronnelle","lemongrass"],
lentils:["lentilles","lentils"],
lettuce:["feuilles de laitue","lettuce leaves"],
liege_syrup:["sirop de Liège", "Liège syrup"],
lima_beans:["haricots de Lima","lima beans"],
lime:["citrons verts","limes"],
limpets:["patelles","limpets"],
lingonberries:["airelles rouges","lingonberries"],
lingonberry_jam:["confiture d'airelles","lingonberry jam"],
liquid_smoke:["fumée liquide","liquid smoke"],
lizano_sauce:["sauce Lizano","Lizano sauce"],
lobster:["langouste","lobster"],
locoto_pepper:["piments locoto","locoto peppers"],
locust_beans:["graines de néré","locust beans"],
long_beans:["haricots longs","long beans"],
long_grain_rice:["riz long grain","long grain rice"],
  longjing_tea: ['thé vert Longjing', 'Longjing green tea'],
  lotus_leaves: ['feuilles de lotus', 'lotus leaves'],
  lotus_root: ['racine de lotus', 'lotus root'],
  lotus_seeds: ['graines de lotus', 'lotus seeds'],
lovage:["livèche", "lovage"],
  luncheon_meat: ['pâté de porc en conserve', 'tinned luncheon meat'],
lupini_beans:["lupins","lupini beans"],
lychee:["litchis","lychees"],
  macadamia_nuts: ['noix de macadamia', 'macadamia nuts'],
macaroni:["macaronis","macaroni"],
mace:["macis","mace"],
mackerel:["maquereau","mackerel"],
madeira_wine:["vin de Madère","Madeira wine"],
  magnolia_leaves: ['feuilles de magnolia séchées', 'dried magnolia leaves'],
maitake_mushrooms:["champignons maitake","maitake mushrooms"],
malagueta_pepper:["piment malagueta","malagueta chilli"],
malsouka_pastry:["pâte malsouka","malsouka pastry"],
malt_extract:["extrait de malt","malt extract"],
malt_vinegar:["vinaigre de malt","malt vinegar"],
  malted_barley_powder: ["poudre de malt d'orge", 'malted barley powder'],
maltose:["maltose","maltose syrup"],
mandarin_pancakes:["crêpes chinoises","mandarin pancakes"],
mango:["mangue","mango"],
maple_syrup:["sirop d'érable","maple syrup"],
marinated_pork:["porc mariné","marinated pork"],
marjoram:["marjolaine","marjoram"],
maroilles_cheese:["maroilles","Maroilles cheese"],
marrow_bone:["os à moelle","marrow bone"],
marsala:["marsala","marsala wine"],
marshmallow_fluff:["crème de guimauve","marshmallow cream"],
marshmallows:["guimauves","marshmallows"],
marzipan:["pâte d'amandes", "marzipan"],
masa_harina:["masa harina","masa harina"],
mascarpone:["mascarpone", "mascarpone"],
massa_de_pimentao:["pâte de poivron rouge", "red pepper paste"],
massale_spice:["épice massalé","massale spice"],
mayonnaise:["mayonnaise","mayonnaise"],
melon_confit:["melon confit","candied melon"],
  menma: ['pousses de bambou fermentées', 'menma'],
merguez:["merguez","merguez sausages"],
milk_powder:["lait en poudre","milk powder"],
millet_couscous:["couscous de mil","millet couscous"],
millet_flour:["farine de mil","millet flour"],
millet_semolina:["semoule de mil","millet semolina"],
mint:["menthe fraîche","fresh mint"],
mirin:["mirin","mirin"],
miso_paste:["pâte de miso","miso paste"],
mitmita:["mitmita","mitmita"],
mochi:["mochi","mochi"],
molasses:["mélasse","molasses"],
monkfish:["lotte", "monkfish"],
montasio_cheese:["montasio", "montasio cheese"],
montbeliard_sausage:["saucisses de Montbéliard","Montbéliard sausages"],
morello_cherries:["griottes","morello cherries"],
mostarda:["mostarda de Crémone", "Cremona mostarda"],
  moth_beans: ['haricots moth', 'moth beans'],
mozzarella:["mozzarella di bufala","buffalo mozzarella"],
msemen:["msemen","msemen"],
  mugwort: ['armoise', 'mugwort'],
mulato_chili:["piment mulato","mulato chilli"],
mullet:["mulets", "grey mullet"],
  mung_bean_flour: ['farine de haricot mungo', 'mung bean flour'],
mung_beans:["haricots mungo","mung beans"],
munster:["munster","Munster cheese"],
mushroom:["champignon","mushroom"],
mushroom_soup:["soupe de champignons","mushroom soup"],
mussels:["moules","mussels"],
mustard:["moutarde","mustard"],
mustard_greens:["feuilles de moutarde","mustard greens"],
mustard_oil:["huile de moutarde","mustard oil"],
mustard_powder:["moutarde en poudre","mustard powder"],
mustard_seeds:["graines de moutarde","mustard seeds"],
mutton_shoulder:["épaule de mouton","mutton shoulder"],
mutton_tallow:["suif de mouton","mutton tallow"],
myoga:["myoga","myoga ginger"],
myrtle_berries:["baies de myrte","myrtle berries"],
myrtle_branches:["branches de myrte","myrtle branches"],
nalca_leaves:["feuilles de nalca","nalca leaves"],
  nanbu_senbei: ['galettes nanbu senbei', 'nanbu senbei crackers'],
  nance: ['nance', 'nance'],
napa_cabbage:["chou chinois","napa cabbage"],
naranjilla:["naranjillas","naranjilla"],
ndole_leaves:["feuilles de ndolé","ndolé leaves"],
nduja:["nduja","'nduja"],
nettles:["orties","nettles"],
  nigella_seeds: ['graines de nigelle', 'nigella seeds'],
nihari_masala:["mélange d'épices nihari","nihari spice mix"],
niter_kibbeh:["beurre épicé niter kibbeh","niter kibbeh spiced butter"],
noni_leaves:["feuilles de noni","noni leaves"],
nori:["feuilles de nori","nori sheets"],
  nuruk: ['nuruk', 'nuruk'],
nutmeg:["noix de muscade","nutmeg"],
oatcakes:["galettes d'avoine","oatcakes"],
oatmeal:["gruau d'avoine","oatmeal"],
oats:["flocons d'avoine", "rolled oats"],
octopus:["poulpe","octopus"],
okra:["gombos","okra"],
old_bay_seasoning:["assaisonnement Old Bay","Old Bay seasoning"],
olive_oil:["huile d'olive","olive oil"],
olives:["olives","olives"],
onion:["oignons","onions"],
onion_powder:["oignon en poudre","onion powder"],
orange:["oranges","oranges"],
orange_blossom_water:["eau de fleur d'oranger","orange blossom water"],
  orange_juice: ["jus d'orange", 'orange juice'],
orange_zest:["zeste d'orange","orange zest"],
orchid_tubers:["tubercules d'orchidée","orchid tubers"],
oregano:["origan","oregano"],
orzo:["pâtes orzo","orzo pasta"],
osmanthus:["fleurs d osmanthe","osmanthus flowers"],
ouzo:["ouzo","ouzo"],
  ox_blood_curd: ['sang de bœuf caillé', 'congealed ox blood'],
oxtail:["queue de bœuf","oxtail"],
oyster_crackers:["petits crackers","oyster crackers"],
oyster_sauce:["sauce d'huître","oyster sauce"],
oysters:["huîtres","oysters"],
padron_peppers:["piments de Padrón","Padrón peppers"],
palm_nut_cream:["crème de noix de palme","palm nut cream"],
palm_nut_pulp:["pulpe de noix de palme","palm nut pulp"],
palm_oil:["huile de palme rouge","red palm oil"],
palm_sugar:["sucre de palme","palm sugar"],
  palm_vinegar: ['vinaigre de palme', 'palm vinegar'],
pancetta:["pancetta", "pancetta"],
panch_phoron:["panch phoron","panch phoron"],
pandan_leaves:["feuilles de pandan","pandan leaves"],
panela:["panela","panela"],
panko:["chapelure panko","panko breadcrumbs"],
papaya_paste:["pâte de papaye verte","green papaya paste"],
  papdi: ['galettes papdi', 'papdi crackers'],
paperbark:["écorce de melaleuca","paperbark"],
paprika:["paprika","paprika"],
parmesan:["parmesan","parmesan"],
parsley:["persil plat","flat-leaf parsley"],
parsnip:["panais","parsnip"],
partridge:["perdrix","partridges"],
pasilla_chili:["piment pasilla","pasilla chilli"],
passion_fruit:["fruits de la passion","passion fruits"],
pasta:["pâtes","pasta"],
pasta_shells:["pâtes à potage","soup pasta"],
pastis:["pastis","pastis"],
pate:["pâté","pâté"],
  pav_bhaji_masala: ['pav bhaji masala', 'pav bhaji masala'],
peach:["pêche","peach"],
peach_syrup:["sirop de pêche","peach syrup"],
peanut_butter:["beurre de cacahuète","peanut butter"],
peanut_oil:["huile d'arachide","peanut oil"],
peanuts:["cacahuètes","peanuts"],
pear:["poire","pear"],
pearl_onions:["oignons grelots","pearl onions"],
pearl_sugar:["sucre perlé","pearl sugar"],
pears:["poires","pears"],
peas:["petits pois","peas"],
  pecans: ['noix de pécan', 'pecans'],
pecorino:["pecorino","pecorino"],
pepper:["poivre noir","black pepper"],
  pepperberry: ['poivre de montagne de Tasmanie', 'Tasmanian mountain pepper'],
  pequi: ['pequi', 'pequi'],
perch:["perche","perch"],
perilla_leaves:["feuilles de périlla","perilla leaves"],
  perilla_seeds: ['graines de périlla', 'perilla seeds'],
  picanha: ['picanha', 'picanha'],
pickle_brine:["saumure de cornichon","pickle brine"],
pickled_beans:["haricots marinés","pickled beans"],
pickled_beets:["betteraves au vinaigre","pickled beetroot"],
  pickled_chili: ['piment mariné chinois', 'Chinese pickled chilli'],
pickled_ginger:["gingembre mariné","pickled ginger"],
pickled_herring:["hareng mariné","pickled herring"],
pickled_mustard_greens:["moutarde chinoise marinée","pickled mustard greens"],
pickled_onions:["oignons au vinaigre","pickled onions"],
pickles:["cornichons","pickles"],
pie_crust:["pâte à tarte","pie crust"],
pig_caul:["crépine de porc","pig's caul"],
pig_tail:["queue de cochon","pig tail"],
pigeon:["pigeons","pigeons"],
pigeon_peas:["pois d'Angole","pigeon peas"],
pike:["brochet","pike"],
pimentos:["piments doux en conserve","tinned pimentos"],
pine_nuts:["pignons de pin","pine nuts"],
pineapple:["ananas","pineapple"],
pineapple_juice:["jus d'ananas","pineapple juice"],
pinkel_sausage:["saucisse Pinkel", "Pinkel sausage"],
pinto_beans:["haricots pinto","pinto beans"],
piquillo_pepper:["poivrons du piquillo", "piquillo peppers"],
piri_piri:["piri-piri","piri-piri"],
  pisco: ['pisco', 'pisco'],
pistachios:["pistaches","pistachios"],
pita_bread:["pains pita","pita breads"],
plain_yogurt:["yaourt nature","plain yoghurt"],
plait_bread:["pain natté","plait bread"],
plantain:["bananes plantain","plantains"],
plantain_chips:["chips de plantain","plantain chips"],
plum_jam:["compote de prunes", "plum compote"],
  plum_sauce: ['sauce aux prunes', 'plum sauce'],
plums:["quetsches","damson plums"],
poblano_pepper:["piments poblano","poblano peppers"],
polenta:["polenta","polenta"],
pollock_roe:["poches d œufs de colin","pollock roe sacs"],
pomegranate:["grenade","pomegranate"],
pomegranate_molasses:["mélasse de grenade","pomegranate molasses"],
ponzu:["ponzu","ponzu"],
  poppy_seed: ['graines de pavot', 'poppy seeds'],
poppy_seed_bun:["pain aux graines de pavot","poppy seed bun"],
pork_belly:["poitrine de porc","pork belly"],
pork_blood:["sang de porc", "pig's blood"],
pork_bones:["os de porc","pork bones"],
pork_broth:["bouillon de porc","pork broth"],
pork_chitterlings:["chaudins de porc","pork chitterlings"],
pork_chops:["côtelettes de porc","pork chops"],
pork_crackling:["grattons de porc","pork crackling"],
pork_cracklings:["couennes de porc frites","pork cracklings"],
pork_ear:["oreille de porc","pig's ear"],
pork_fat:["gras de porc","pork fat"],
  pork_fatback: ['lard dorsal', 'pork fatback'],
  pork_floss: ['porc séché effiloché', 'pork floss'],
pork_head:["tête de porc","pig's head"],
  pork_heart: ['cœur de porc', 'pork heart'],
  pork_intestines: ['intestins de porc', 'pork intestines'],
pork_kidney:["rognons de porc","pork kidney"],
pork_knuckle:["jarret de porc fumé","smoked pork knuckle"],
pork_liver:["foie de porc","pork liver"],
pork_loin:["longe de porc","pork loin"],
pork_lung:["poumon de porc","pork lung"],
pork_ribs:["travers de porc","pork ribs"],
pork_rind:["chicharron","pork rind"],
pork_rinds:["couennes de porc","pork rinds"],
pork_roll:["pork roll","pork roll"],
pork_sausage:["saucisses de porc","pork sausages"],
pork_shank:["jarret de porc","pork shank"],
pork_shoulder:["échine de porc","pork shoulder"],
pork_skin:["couenne de porc","pork skin"],
pork_snout:["museau de porc","pork snout"],
pork_stomach:["panse de porc", "pig's stomach"],
pork_tail:["queue de porc","pork tail"],
pork_tongue:["langues de porc","pork tongues"],
  pork_tripe: ['estomac de porc', 'pork stomach'],
pork_trotters:["pieds de porc","pig's trotters"],
port_wine:["porto", "port wine"],
potato:["pommes de terre","potatoes"],
potato_starch:["fécule de pomme de terre","potato starch"],
powdered_sugar:["sucre glace","icing sugar"],
praline_rose:["pralines roses","pink pralines"],
precooked_corn_flour:["farine de maïs précuite","precooked maize flour"],
preserved_lemon:["citrons confits","preserved lemons"],
preserved_mustard_greens:["moutarde fermentée","preserved mustard greens"],
presunto:["presunto","presunto"],
processed_cheese:["fromage fondu","processed cheese"],
prosciutto:["jambon de Parme","prosciutto"],
prosecco:["prosecco","prosecco"],
provolone:["provolone","provolone"],
prunes:["pruneaux","prunes"],
puff_pastry:["pâte feuilletée","puff pastry"],
  puffed_rice: ['riz soufflé', 'puffed rice'],
  pufferfish: ['poisson-globe', 'pufferfish'],
puha:["pūhā","pūhā"],
pumpkin:["potiron","pumpkin"],
pumpkin_leaves:["feuilles de potiron","pumpkin leaves"],
pumpkin_seed_oil:["huile de pépins de courge", "pumpkin seed oil"],
pumpkin_seeds:["graines de courge","pumpkin seeds"],
  purple_corn: ['maïs violet', 'purple corn'],
quail_egg:["œufs de caille","quail eggs"],
  quandong: ['quandong', 'quandong'],
  queijo_manteiga: ['queijo manteiga', 'queijo manteiga'],
  queijo_minas: ['fromage du Minas', 'Minas cheese'],
quesillo:["quesillo d'Oaxaca","Oaxaca quesillo"],
queso_fresco:["fromage frais latino","queso fresco"],
queso_paraguay:["fromage Paraguay","queso Paraguay"],
  queso_seco: ["fromage sec d'Amérique centrale", 'Central American dry cheese'],
quince:["coing","quince"],
rabbit:["lapin","rabbit"],
raclette_cheese:["fromage à raclette", "raclette cheese"],
radish:["radis","radish"],
raisins:["raisins secs","raisins"],
ram_testicles:["testicules de bélier","ram testicles"],
ramen_noodles:["nouilles à ramen","ramen noodles"],
ras_el_hanout:["ras el-hanout","ras el hanout"],
raspberries:["framboises", "raspberries"],
ravioli:["raviolis frais","fresh ravioli"],
razor_clams:["couteaux de mer","razor clams"],
reblochon:["reblochon fermier","farmhouse reblochon"],
  recado_negro: ['recado negro', 'recado negro'],
recado_rojo:["recado rojo","recado rojo"],
red_bean_paste:["pâte de haricots rouges","red bean paste"],
red_cabbage:["chou rouge", "red cabbage"],
red_chili:["piments rouges","red chillies"],
red_currant_jelly:["gelée de groseille","redcurrant jelly"],
red_dates:["jujubes séchées","dried red dates"],
red_food_coloring:["colorant alimentaire rouge","red food coloring"],
red_kidney_beans:["haricots rouges","red kidney beans"],
red_lentils:["lentilles corail","red lentils"],
  red_miso: ['miso rouge', 'red miso'],
red_mullet:["rougets","red mullet"],
red_onion:["oignons rouges","red onions"],
red_pepper:["poivrons rouges","red peppers"],
red_snapper:["vivaneau","red snapper"],
red_wine:["vin rouge","red wine"],
red_wine_vinegar:["vinaigre de vin rouge","red wine vinegar"],
  red_yeast_rice: ['riz rouge fermenté', 'red yeast rice'],
redcurrants:["groseilles", "redcurrants"],
refried_beans:["haricots refrits","refried beans"],
reindeer:["renne", "reindeer"],
reindeer_tongue:["langues de renne","reindeer tongues"],
relajo_spices:["épices relajo","relajo spices"],
relish:["relish","relish"],
rennet:["présure","rennet"],
rice:["riz","rice"],
rice_cakes:["gâteaux de riz","rice cakes"],
rice_crackers:["galettes de riz","rice crackers"],
rice_flour:["farine de riz","rice flour"],
rice_noodles:["nouilles de riz","rice noodles"],
rice_paper:["papier azyme","edible wafer paper"],
  rice_syrup: ['sirop de riz', 'rice syrup'],
rice_vermicelli:["vermicelles de riz","rice vermicelli"],
rice_vinegar:["vinaigre de riz","rice vinegar"],
rice_wine:["vin de riz","rice wine"],
ricotta:["ricotta", "ricotta"],
ricotta_salata:["ricotta salata", "salted ricotta"],
riesling:["riesling d'Alsace","Alsatian riesling"],
rigatoni:["rigatoni","rigatoni"],
ripe_banana:["bananes bien mûres","very ripe bananas"],
ripe_plantain:["plantains mûrs","ripe plantains"],
ripe_tomato:["tomates bien mûres","ripe tomatoes"],
river_prawns:["crevettes de rivière","river prawns"],
roasted_red_pepper:["poivron rouge rôti","roasted red pepper"],
  roasted_soybean_powder: ['poudre de soja grillé', 'roasted soybean powder'],
rock_sugar:["sucre candi","rock sugar"],
rockfish:["poissons de roche","rockfish"],
rocoto_pepper:["piments rocoto","rocoto peppers"],
roquefort_cheese:["roquefort","Roquefort cheese"],
rose_water:["eau de rose","rose water"],
  roselle_leaves: ["feuilles d'oseille de Guinée", 'roselle leaves'],
rosemary:["romarin","rosemary"],
rum:["rhum","rum"],
rustic_bread:["pain de campagne","rustic bread"],
rye_bread:["pain de seigle","rye bread"],
rye_flour:["farine de seigle","rye flour"],
sacha_culantro:["sacha culantro","sacha culantro"],
saffron:["safran","saffron"],
sage:["feuilles de sauge", "sage leaves"],
sago_starch:["fécule de sagou","sago starch"],
saint_marcellin:["saint-marcellin","Saint-Marcellin cheese"],
sake:["saké","sake"],
sakhan_wood:["bois de sakhan","sakhan wood"],
salad_burnet:["pimprenelle","salad burnet"],
salami:["salami","salami"],
  salep: ['salep', 'salep'],
salmon:["saumon","salmon"],
salmon_roe:["œufs de saumon","salmon roe"],
  salsa: ['sauce salsa', 'salsa'],
salt:["sel","salt"],
salt_cod:["morue salée","salt cod"],
salt_pork:["lard salé","salt pork"],
salted_anchovies:["anchois au sel","salted anchovies"],
salted_beef:["bœuf salé","salt beef"],
salted_butter:["beurre demi-sel","salted butter"],
  salted_egg_yolk: ["jaune d'œuf salé", 'salted egg yolk'],
  salted_fish: ['poisson salé', 'salted fish'],
salted_herring:["harengs salés","salted herring"],
  salted_jellyfish: ['méduse salée', 'salted jellyfish'],
salted_pork:["porc salé","salted pork"],
  salted_shrimp: ['crevettes salées', 'salted shrimp'],
  sambar_powder: ['poudre à sambar', 'sambar powder'],
san_marzano_tomato:["tomates San Marzano","San Marzano tomatoes"],
  sand_ginger: ['gingembre des sables', 'sand ginger'],
sardines:["sardines entières","whole sardines"],
saskatoon_berries:["baies de Saskatoon","Saskatoon berries"],
sauerkraut:["choucroute crue","raw sauerkraut"],
sausage:["saucisse","sausage"],
sausage_casings:["boyaux de porc","sausage casings"],
savory:["sarriette","savory"],
savoy_cabbage:["chou de Milan", "savoy cabbage"],
scabbard_fish:["poisson-sabre noir","black scabbardfish"],
scallion:["ciboule","scallion"],
scallops:["noix de Saint-Jacques","scallops"],
scent_leaf:["basilic africain","scent leaf"],
scotch_bonnet:["piments scotch bonnet","scotch bonnet chillies"],
scotch_bonnet_pepper:["piment scotch bonnet","scotch bonnet pepper"],
sea_bass:["bar","sea bass"],
sea_bream:["dorade","sea bream"],
  sea_grapes: ['raisins de mer', 'sea grapes'],
sea_salt:["sel de mer","sea salt"],
sea_urchin:["oursin","sea urchin"],
  seaweed: ['algue grillée', 'toasted seaweed'],
semolina:["semoule","semolina"],
semolina_flour:["farine de semoule fine","fine semolina flour"],
serrano_ham:["jambon serrano","serrano ham"],
serrano_pepper:["piments serrano","serrano chillies"],
sesame_oil:["huile de sésame","sesame oil"],
sesame_paste:["pâte de sésame","sesame paste"],
sesame_roll:["pains au sésame","sesame rolls"],
sesame_seeds:["graines de sésame","sesame seeds"],
  sev: ['sev', 'sev'],
  shacha_sauce: ['sauce shacha', 'shacha sauce'],
shad:["alose","shad"],
shallot:["échalotes","shallots"],
shaoxing_wine:["vin de Shaoxing","Shaoxing wine"],
sheep_blood:["sang de mouton","sheep's blood"],
sheep_cheese:["fromages de brebis secs","dry ewe's cheese"],
sheep_head:["tête de mouton","sheep's head"],
sheep_milk_cheese:["fromage de brebis","sheep's milk cheese"],
sheep_pluck:["fressure d'agneau", "lamb pluck"],
sheep_ricotta:["ricotta de brebis","sheep's ricotta"],
sheep_suet:["suif de mouton en morceaux","sheep suet"],
sherry:["xérès","sherry"],
sherry_vinegar:["vinaigre de Xérès","sherry vinegar"],
shichimi:["shichimi togarashi","shichimi togarashi"],
shiitake_mushrooms:["champignons shiitake","shiitake mushrooms"],
shiro_powder:["farine de shiro","shiro powder"],
shiso:["feuilles de shiso","shiso leaves"],
  short_grain_rice: ['riz rond', 'short-grain rice'],
shortcrust_pastry:["pâte brisée","shortcrust pastry"],
  shortening: ['graisse végétale', 'vegetable shortening'],
shrimp:["crevettes","prawns"],
shrimp_paste:["pâte de crevette","shrimp paste"],
sichuan_pepper:["poivre de Sichuan","Sichuan pepper"],
sichuan_peppercorns:["poivre du Sichuan","Sichuan peppercorns"],
silken_tofu:["tofu soyeux","silken tofu"],
sirloin_steak:["faux-filet","sirloin steak"],
  small_fish: ['petits poissons entiers', 'small whole fish'],
small_shrimp:["crevettes grises","small grey shrimps"],
smen:["smen","smen"],
smetana:["smetana","smetana"],
smoked_bacon:["lard fumé","smoked bacon"],
smoked_chicken:["poulet fumé","smoked chicken"],
smoked_dried_tuna:["thon fumé séché","smoked dried tuna"],
smoked_fish:["poisson fumé","smoked fish"],
smoked_haddock:["églefin fumé", "smoked haddock"],
smoked_ham:["jambon fumé","smoked ham"],
smoked_paprika:["paprika fumé","smoked paprika"],
smoked_pork_collar:["échine de porc fumée","smoked pork collar"],
smoked_pork_loin:["palette de porc fumée","smoked pork loin"],
smoked_pork_ribs:["travers de porc fumés","smoked pork ribs"],
smoked_sausage:["saucisse fumée","smoked sausage"],
smoked_shrimp:["crevettes fumées","smoked shrimp"],
smoked_trout:["saumon fumé à l'aulne","alder-smoked salmon"],
snails:["escargots", "snails"],
sobrassada:["sobrassada", "sobrassada"],
sofrito:["sofrito","sofrito"],
sorghum_flour:["farine de sorgho","sorghum flour"],
sorghum_leaves:["feuilles de sorgho rouge","red sorghum leaves"],
sorrel:["oseille", "sorrel"],
sour_cream:["crème aigre","sour cream"],
sour_milk:["lait caillé","soured milk"],
sour_orange:["orange amère","sour orange"],
sour_orange_juice:["jus d'orange amère","sour orange juice"],
sour_whey:["petit-lait aigre","sour whey"],
sourdough_starter:["levain naturel","sourdough starter"],
  soy_milk: ['lait de soja', 'soy milk'],
soy_sauce:["sauce soja","soy sauce"],
soybeans:["graines de soja","soybeans"],
spaghetti:["spaghetti","spaghetti"],
spam:["Spam","Spam"],
sparkling_water:["eau gazeuse","sparkling water"],
sparkling_wine:["vin mousseux","sparkling wine"],
speculoos_spice:["mélange d'épices à spéculoos", "speculoos spice mix"],
spinach:["épinards","spinach"],
split_peas:["pois cassés","split peas"],
sponge_cake:["biscuit de Savoie","sponge cake"],
spot_prawns:["crevettes tachetées","spot prawns"],
spring_onion:["ciboules","spring onions"],
  sprinkles: ['billes de sucre colorées', 'sugar sprinkles'],
squid:["calmar","squid"],
squid_ink:["encre de seiche", "squid ink"],
  ssamjang: ['ssamjang', 'ssamjang'],
stale_bread:["pain rassis","stale bread"],
star_anise:["badiane","star anise"],
  steamed_buns: ['petits pains vapeur', 'steamed buns'],
stockfish:["stockfisch", "stockfish"],
stone_flower:["pierre de fleur","stone flower"],
stout:["stout","stout"],
strasbourg_sausage:["saucisses de Strasbourg","Strasbourg sausages"],
strawberries:["fraises","strawberries"],
suckling_pig:["cochon de lait","suckling pig"],
sugar:["sucre","sugar"],
  sugar_cubes: ['sucre en morceaux', 'sugar cubes'],
sulguni_cheese:["fromage soulgouni","sulguni cheese"],
sultanas:["raisins de Smyrne","sultanas"],
sumac:["sumac","sumac"],
sunflower_oil:["huile de tournesol","sunflower oil"],
sunflower_seeds:["graines de tournesol","sunflower seeds"],
sushi_rice:["riz à sushi","sushi rice"],
swede:["rutabaga", "swede"],
sweet_bean_sauce:["sauce de soja sucrée","sweet bean sauce"],
sweet_mustard:["moutarde douce bavaroise", "sweet Bavarian mustard"],
sweet_onion:["oignon doux","sweet onion"],
sweet_paprika:["paprika doux","sweet paprika"],
sweet_potato:["patates douces","sweet potatoes"],
sweet_potato_leaves:["feuilles de patate douce","sweet potato leaves"],
  sweet_potato_noodles: ['vermicelles de patate douce', 'sweet potato noodles'],
sweet_potato_starch:["fécule de patate douce","sweet potato starch"],
  sweet_soy_sauce: ['soja sucré', 'sweetened soy sauce'],
sweetcorn:["maïs doux","sweetcorn"],
swiss_chard:["blettes","chard"],
swiss_cheese:["fromage suisse","Swiss cheese"],
tabil:["tabil","tabil"],
tahini:["tahini","tahini"],
takoyaki_sauce:["sauce takoyaki","takoyaki sauce"],
tamarind_paste:["pâte de tamarin","tamarind paste"],
  tangerine: ['mandarines', 'tangerines'],
tansy:["tanaisie","tansy"],
tapioca:["tapioca","tapioca"],
  tapioca_pearls: ['perles de tapioca', 'tapioca pearls'],
tapioca_starch:["fécule de tapioca","tapioca starch"],
taro_leaves:["feuilles de taro","taro leaves"],
taro_root:["taro","taro root"],
tarragon:["estragon","tarragon"],
teak_leaves:["feuilles de teck","teak leaves"],
teff_flour:["farine de teff","teff flour"],
tempeh:["tempeh","tempeh"],
thai_basil:["basilic thaï","Thai basil"],
  thekera: ['thekera séché', 'dried thekera'],
thick_rice_noodles:["nouilles de riz épaisses","thick rice noodles"],
thyme:["thym","thyme"],
ti_leaves:["feuilles de ti","ti leaves"],
tiger_nuts:["souchets","tiger nuts"],
tilapia:["tilapia","tilapia"],
tkemali_sauce:["sauce tkemali","tkemali sauce"],
tofu:["tofu","tofu"],
  tofu_skin: ['feuilles de tofu', 'tofu skin'],
tomatillo:["tomatillo","tomatillo"],
tomatillos:["tomatilles","tomatillos"],
tomato:["tomates","tomatoes"],
tomato_paste:["concentré de tomate","tomato paste"],
tomato_puree:["purée de tomate","tomato purée"],
tomato_sauce:["sauce tomate","tomato sauce"],
tome_fraiche:["tome fraîche","fresh tome cheese"],
tomme_fraiche:["tomme fraîche de l'Aubrac","fresh Aubrac tomme"],
tonnarelli_pasta:["tonnarelli","tonnarelli pasta"],
  toor_dal: ["pois d'Angole cassés", 'toor dal'],
torch_ginger:["fleur de gingembre","torch ginger flower"],
tortilla:["tortilla","tortilla"],
tortilla_chips:["chips de maïs","tortilla chips"],
toulouse_sausage:["saucisses de Toulouse","Toulouse sausages"],
tripe:["tripes","tripe"],
trout:["truite","trout"],
  tucuma: ['tucumã', 'tucumã'],
tucupi:["tucupi","tucupi"],
tuna:["thon rouge","tuna"],
turkey:["dinde","turkey"],
turkey_breast:["blanc de dinde","turkey breast"],
turmeric:["curcuma","turmeric"],
turnip:["navets","turnips"],
turnip_greens:["grelos","turnip greens"],
turnip_tops:["fanes de navet","turnip tops"],
tuscan_kale:["chou noir toscan","Tuscan kale"],
tvorog:["tvorog","tvorog"],
udon_noodles:["nouilles udon","udon noodles"],
urad_dal:["lentilles urad","urad dal"],
vacherin_cheese:["vacherin fribourgeois","vacherin fribourgeois"],
vanilla:["extrait de vanille","vanilla extract"],
vanilla_custard_powder:["poudre pour crème pâtissière","vanilla custard powder"],
vanilla_ice_cream:["glace vanille","vanilla ice cream"],
veal:["veau","veal"],
veal_chop:["côtes de veau","veal chops"],
veal_escalope:["escalopes de veau","veal escalopes"],
veal_foot:["pied de veau","veal foot"],
veal_shank:["jarret de veau","veal shank"],
veal_shoulder:["épaule de veau","veal shoulder"],
venison:["viande de gibier","venison"],
vergeoise:["vergeoise brune","brown beet sugar"],
vermicelli:["vermicelles","vermicelli"],
vialone_rice:["riz vialone nano", "vialone nano rice"],
vin_jaune:["vin jaune","vin jaune"],
vinegar:["vinaigre","vinegar"],
vodka:["vodka","vodka"],
wakame:["algues wakame","wakame seaweed"],
  wallaby: ['filet de wallaby', 'wallaby fillet'],
walnut_oil:["huile de noix","walnut oil"],
walnuts:["noix","walnuts"],
warm_water:["eau tiède","warm water"],
warqa_sheets:["feuilles de warqa","warqa pastry sheets"],
wasabi:["wasabi","wasabi"],
water:["eau","water"],
  water_chestnuts: ["châtaignes d'eau", 'water chestnuts'],
water_spinach:["liseron d'eau","water spinach"],
watercress:["cresson","watercress"],
  watermelon: ['pastèque', 'watermelon'],
wedge_clams:["tellines","wedge clams"],
whale_skin:["peau et lard de baleine","whale skin and blubber"],
wheat_berries:["grains de blé","wheat berries"],
wheat_noodles:["nouilles de blé","wheat noodles"],
wheat_starch:["amidon de blé","wheat starch"],
whelks:["bulots","whelks"],
whisky:["whisky", "whisky"],
white_asparagus:["asperges blanches", "white asparagus"],
white_beans:["haricots blancs lingots","white haricot beans"],
white_bread:["pain de mie","white bread"],
white_cornmeal:["farine de maïs blanc","white maize meal"],
white_fish:["poisson blanc à chair ferme","firm white fish"],
white_onion:["oignon blanc","white onion"],
white_pepper:["poivre blanc","white pepper"],
white_rum:["rhum blanc","white rum"],
white_sausage:["saucisses blanches", "white sausages"],
white_truffle:["truffe blanche","white truffle"],
white_vinegar:["vinaigre blanc","white vinegar"],
white_wine:["vin blanc sec","dry white wine"],
white_wine_vinegar:["vinaigre de vin blanc","white wine vinegar"],
whitebait:["alevins","whitebait"],
whitefish:["poisson blanc d'eau douce","whitefish"],
whiting:["merlan","whiting"],
whole_duck:["canard entier","whole duck"],
whole_fish:["poisson entier","whole fish"],
whole_milk:["lait entier","whole milk"],
whole_wheat_flour:["farine de blé complet","whole wheat flour"],
wild_boar:["sanglier","wild boar"],
wild_fennel:["fenouil sauvage","wild fennel"],
wind_dried_mutton:["mouton séché au vent", "wind-dried mutton"],
wiri_wiri_pepper:["piments wiri wiri","wiri wiri peppers"],
  witchetty_grubs: ['larves witchetty', 'witchetty grubs'],
wonton_wrapper:["feuilles à raviolis","wonton wrappers"],
wood_ear_mushrooms:["champignons noirs","wood ear mushrooms"],
worcestershire:["sauce Worcestershire","Worcestershire sauce"],
xawaash:["xawaash","xawaash"],
xawaash_spice:["épice xawaash","xawaash spice"],
  yak_butter: ['beurre de yak', 'yak butter'],
yam:["igname","yam"],
yautia:["yautía","yautía"],
  yeast_extract: ['pâte de levure salée', 'salty yeast extract'],
yellow_carrot:["carottes jaunes","yellow carrots"],
yellow_lentils:["lentilles jaunes","yellow lentils"],
yellow_peas:["pois jaunes","yellow peas"],
yellow_pepper:["poivron jaune","yellow pepper"],
  yellow_potato: ['pomme de terre jaune', 'yellow potato'],
yellow_soybean_paste:["pâte de soja jaune","yellow soybean paste"],
  yerba_mate: ['yerba maté', 'yerba mate'],
  youtiao: ['beignet de pâte youtiao', 'youtiao dough stick'],
yuzu:["yuzu","yuzu"],
ziti:["ziti","ziti"],
zucchini:["courgettes","courgettes"],
zucchini_flowers:["fleurs de courgette","courgette flowers"]
};
